all:
	clang++ Line.cpp -c
	clang++ Circle.cpp -c
	clang++ Point.cpp -c
	clang++ main.cpp -c
	clang++ Shape.cpp -c
	clang++ visitor.cpp -c
	clang++ Line.o Circle.o Point.o Shape.o main.o visitor.o -o test.out
	rm -rf *.o