all:
	g++ Point.cpp -c
	g++ Circle.cpp -c
	g++ test.cpp -c
	g++ Point.o Circle.o test.o -o test.out
	rm -f *.o
clang:
	clang++ Point.cpp -c
	clang++ Line.cpp -c
	clang++ test.cpp -c
	clang++ Point.o Circle.o test.o -o test.out
	rm -f *.o